# Generated by Django 6.0.4 on 2026-05-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="trust_strikes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Incremented on: owner cancels confirmed reservation, confirmed report, dispute opened against user.",
            ),
        ),
    ]
