# Generated by Django 6.0.4 on 2026-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_trust_strikes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="category_affinity",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-category interaction weight vector, recomputed by Celery after every 10 interactions.",
            ),
        ),
    ]
