# Generated by Django 6.0.4 on 2026-05-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_category_affinity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_step",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0=incomplete, 1=profile_done, 2=first_listing, 3=complete",
            ),
        ),
    ]
