# Generated by Django 6.0.4 on 2026-05-14 19:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_assistant_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="assistant_notes",
            field=models.TextField(
                blank=True,
                help_text="Short memory summary carried across assistant sessions. Populated by Claude after each thread ends.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                db_index=True,
                default=accounts.models._gen_referral_code,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_on_leaderboard",
            field=models.BooleanField(
                default=True,
                help_text="Opt-in to the campus leaderboard. Default True.",
            ),
        ),
    ]
