# Generated by Django 6.0.4 on 2026-05-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_phase25_semantic_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="theme",
            field=models.JSONField(
                blank=True,
                help_text="White-label theme overrides. Keys: primary_color, logo_url, font_family, hero_message.",
                null=True,
            ),
        ),
    ]
