# Generated by Django 6.0.4 on 2026-07-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_phase27_campus_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="assistant_notes",
        ),
    ]
