# Generated by Django 6.0.8 on 2026-09-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_user_assistant_notes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="campussubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_session_id", ""), _negated=True),
                fields=("stripe_session_id",),
                name="unique_campus_subscription_session",
            ),
        ),
    ]
