from django.urls import path

from .views import (
    CampusAnalyticsView,
    CampusAnalyticsExportView,
    ImpactBenchmarkView,
    DashboardView,
    EventStreamView,
    PushSubscribeView,
    PushUnsubscribeView,
    VapidPublicKeyView,
    DonateListingView,
    DuplicateCheckView,
    GenerateDescriptionView,
    InsightsView,
    ImpactView,
    ListingAnalyticsView,
    ListingBulkUpdateView,
    ParseSearchView,
    ListingDetailView,
    ListingGalleryImageView,
    ListingGalleryUploadView,
    ListingListCreateView,
    PricingHintView,
    RepostListingView,
    RescueSuggestionsView,
    ListingReportListCreateView,
    ListingUpdateListCreateView,
    VisionAutofillView,
    MatchCenterView,
    MoveOutTaskDetailView,
    MoveOutTaskListCreateView,
    NotificationDetailView,
    NotificationDigestView,
    NotificationListView,
    NotificationPreferenceView,
    NotificationReadAllView,
    PublishPresetsView,
    ReservationDetailView,
    ReservationFeedbackListCreateView,
    ReservationListCreateView,
    ReservationMessageListCreateView,
    RescueRequestDetailView,
    RescueRequestListCreateView,
    RescueRequestMatchView,
    RoomScanImageUploadView,
    RoomScanItemCreateView,
    RoomScanItemDetailView,
    RoomScanSessionBatchUpdateView,
    RoomScanSessionBoardView,
    RoomScanSessionBulkConvertView,
    AiDetectItemsView,
    AiDetectStatusView,
    RoomScanSessionDetailView,
    RoomScanSessionListCreateView,
    RoomScanSessionPlanView,
    RoomScanSessionPublishQueueView,
    RoomScanSessionPublishSelectedView,
    SavedListingListView,
    SavedListingToggleView,
    TrustOverviewView,
    ListingUploadUrlView,
    BlockUserView,
    DisputeDetailView,
    DisputeListView,
    ModerationActionView,
    ModerationQueueView,
    ReservationDisputeView,
    ReservationCalendarView,
    ReservationEnRouteView,
    ReservationSlotsView,
    ReservationVerifyPinView,
    CampusSubscribeView,
    DonationIntentCreateView,
    ListingBoostConfirmView,
    ListingBoostView,
    OrganizationListView,
    StripeWebhookView,
    DemandForecastView,
    PriceContextView,
    QualityHintsDismissView,
    SuggestCategoriesView,
    AnnouncementDetailView,
    AnnouncementListCreateView,
    BuildingLeaderboardView,
    LeaderboardView,
    ReservationThankView,
    BatchConfirmReservationsView,
    CollectionEventDetailView,
    CollectionEventListCreateView,
    RouteOptimiseView,
    StorageHoldDetailView,
    StorageHoldListCreateView,
    BuildingCoordListCreateView,
    MapDataView,
    ProximityRouteView,
    SavedSearchDetailView,
    SavedSearchListCreateView,
    SemanticSearchView,
    TrendingListingsView,
    CampusThemeView,
    EmbedListingsView,
    PartnerKeyProvisionView,
    PartnerListingsView,
    PartnerReservationsView,
    PartnerUsageView,
    PartnerWebhookDetailView,
    PartnerWebhookListCreateView,
)

urlpatterns = [
    path("impact", ImpactView.as_view(), name="impact"),
    path("events", EventStreamView.as_view(), name="event-stream"),
    path("push/vapid-key", VapidPublicKeyView.as_view(), name="push-vapid-key"),
    path("push/subscribe", PushSubscribeView.as_view(), name="push-subscribe"),
    path("push/unsubscribe", PushUnsubscribeView.as_view(), name="push-unsubscribe"),
    path("campus-analytics", CampusAnalyticsView.as_view(), name="campus-analytics"),
    path("campus-analytics/export.csv", CampusAnalyticsExportView.as_view(), name="campus-analytics-export"),
    path("impact/benchmark", ImpactBenchmarkView.as_view(), name="impact-benchmark"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("insights", InsightsView.as_view(), name="insights"),
    path("match-center", MatchCenterView.as_view(), name="match-center"),
    path("publish-presets", PublishPresetsView.as_view(), name="publish-presets"),
    path("listings", ListingListCreateView.as_view(), name="listings-list"),
    path("listings/bulk-update", ListingBulkUpdateView.as_view(), name="listings-bulk-update"),
    path("listings/generate-description", GenerateDescriptionView.as_view(), name="listings-generate-description"),
    path("listings/parse-search", ParseSearchView.as_view(), name="listings-parse-search"),
    path("listings/pricing-hint", PricingHintView.as_view(), name="listings-pricing-hint"),
    path("listings/vision-autofill", VisionAutofillView.as_view(), name="listings-vision-autofill"),
    path("listings/check-duplicate", DuplicateCheckView.as_view(), name="listings-check-duplicate"),
    path("listings/rescue-suggestions", RescueSuggestionsView.as_view(), name="listings-rescue-suggestions"),
    path("listings/<int:pk>/upload-url", ListingUploadUrlView.as_view(), name="listings-upload-url"),
    path("listings/<int:pk>/analytics", ListingAnalyticsView.as_view(), name="listings-analytics"),
    path("listings/<int:pk>/repost", RepostListingView.as_view(), name="listings-repost"),
    path("listings/<int:pk>/donate", DonateListingView.as_view(), name="listings-donate"),
    path("listings/<int:pk>", ListingDetailView.as_view(), name="listings-detail"),
    path("listings/<int:pk>/save", SavedListingToggleView.as_view(), name="listings-save"),
    path("listings/<int:pk>/reports", ListingReportListCreateView.as_view(), name="listings-reports"),
    path("listings/<int:pk>/updates", ListingUpdateListCreateView.as_view(), name="listings-updates"),
    path("listings/<int:pk>/images", ListingGalleryUploadView.as_view(), name="listings-gallery"),
    path("listings/<int:pk>/images/<int:image_id>", ListingGalleryImageView.as_view(), name="listings-gallery-image"),
    path("reservations", ReservationListCreateView.as_view(), name="reservations-list"),
    path("reservations/<int:pk>", ReservationDetailView.as_view(), name="reservations-detail"),
    path("reservations/<int:pk>/feedback", ReservationFeedbackListCreateView.as_view(), name="reservations-feedback"),
    path("reservations/<int:pk>/messages", ReservationMessageListCreateView.as_view(), name="reservations-messages"),
    path("requests", RescueRequestListCreateView.as_view(), name="requests-list"),
    path("requests/<int:pk>", RescueRequestDetailView.as_view(), name="requests-detail"),
    path("requests/<int:pk>/match", RescueRequestMatchView.as_view(), name="requests-match"),
    path("saved-listings", SavedListingListView.as_view(), name="saved-listings"),
    path("trust/me", TrustOverviewView.as_view(), name="trust-overview"),
    path("notifications", NotificationListView.as_view(), name="notifications-list"),
    path("notifications/read-all", NotificationReadAllView.as_view(), name="notifications-read-all"),
    path("notifications/digest", NotificationDigestView.as_view(), name="notifications-digest"),
    path("notifications/preferences", NotificationPreferenceView.as_view(), name="notifications-preferences"),
    path("notifications/<int:pk>", NotificationDetailView.as_view(), name="notifications-detail"),
    path("scan-sessions", RoomScanSessionListCreateView.as_view(), name="scan-sessions-list"),
    path("scan-sessions/<int:pk>", RoomScanSessionDetailView.as_view(), name="scan-sessions-detail"),
    path("scan-sessions/<int:pk>/images", RoomScanImageUploadView.as_view(), name="scan-sessions-images"),
    path("scan-sessions/<int:pk>/items", RoomScanItemCreateView.as_view(), name="scan-sessions-items"),
    path("scan-sessions/<int:pk>/board", RoomScanSessionBoardView.as_view(), name="scan-sessions-board"),
    path("scan-sessions/<int:pk>/plan", RoomScanSessionPlanView.as_view(), name="scan-sessions-plan"),
    path("scan-sessions/<int:pk>/tasks", MoveOutTaskListCreateView.as_view(), name="scan-sessions-tasks"),
    path("scan-sessions/<int:pk>/publish-queue", RoomScanSessionPublishQueueView.as_view(), name="scan-sessions-publish-queue"),
    path("scan-sessions/<int:pk>/batch-update", RoomScanSessionBatchUpdateView.as_view(), name="scan-sessions-batch-update"),
    path("scan-sessions/<int:pk>/publish-selected", RoomScanSessionPublishSelectedView.as_view(), name="scan-sessions-publish-selected"),
    path("scan-sessions/<int:pk>/bulk-convert", RoomScanSessionBulkConvertView.as_view(), name="scan-sessions-bulk-convert"),
    path("scan-sessions/<int:pk>/ai-detect", AiDetectItemsView.as_view(), name="scan-sessions-ai-detect"),
    path("scan-sessions/<int:pk>/ai-detect/status", AiDetectStatusView.as_view(), name="scan-sessions-ai-detect-status"),
    path("scan-items/<int:pk>", RoomScanItemDetailView.as_view(), name="scan-items-detail"),
    path("scan-tasks/<int:pk>", MoveOutTaskDetailView.as_view(), name="scan-tasks-detail"),
    path("users/<int:pk>/block", BlockUserView.as_view(), name="user-block"),
    path("reservations/<int:pk>/dispute", ReservationDisputeView.as_view(), name="reservation-dispute"),
    path("reservations/<int:pk>/slots", ReservationSlotsView.as_view(), name="reservation-slots"),
    path("reservations/<int:pk>/verify-pin", ReservationVerifyPinView.as_view(), name="reservation-verify-pin"),
    path("reservations/<int:pk>/en-route", ReservationEnRouteView.as_view(), name="reservation-en-route"),
    path("reservations/<int:pk>/calendar.ics", ReservationCalendarView.as_view(), name="reservation-calendar"),
    path("disputes", DisputeListView.as_view(), name="dispute-list"),
    path("disputes/<int:pk>", DisputeDetailView.as_view(), name="dispute-detail"),
    path("admin/moderation", ModerationQueueView.as_view(), name="moderation-queue"),
    path("admin/listings/<int:pk>/moderate", ModerationActionView.as_view(), name="moderation-action"),
    # Phase 18 — Platform Intelligence
    path("listings/demand-forecast", DemandForecastView.as_view(), name="listings-demand-forecast"),
    path("listings/price-context", PriceContextView.as_view(), name="listings-price-context"),
    path("listings/suggest-categories", SuggestCategoriesView.as_view(), name="listings-suggest-categories"),
    path("listings/<int:pk>/dismiss-hints", QualityHintsDismissView.as_view(), name="listings-dismiss-hints"),
    # Phase 17 — Revenue & Sustainability
    path("campus/subscribe", CampusSubscribeView.as_view(), name="campus-subscribe"),
    path("stripe/webhook", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("listings/<int:pk>/boost", ListingBoostView.as_view(), name="listing-boost"),
    path("listings/<int:pk>/boost-confirm", ListingBoostConfirmView.as_view(), name="listing-boost-confirm"),
    path("listings/<int:pk>/donate-intent", DonationIntentCreateView.as_view(), name="listing-donate-intent"),
    path("organizations", OrganizationListView.as_view(), name="organization-list"),
    # Phase 20 — Reporting & Data Exports
    path("campus-analytics/export.csv", CampusAnalyticsExportView.as_view(), name="campus-analytics-export"),
    path("impact/benchmark", ImpactBenchmarkView.as_view(), name="impact-benchmark"),
    # Phase 24 — Logistics & Batching
    path("logistics/batch-confirm", BatchConfirmReservationsView.as_view(), name="logistics-batch-confirm"),
    path("logistics/holds", StorageHoldListCreateView.as_view(), name="logistics-holds"),
    path("logistics/holds/<int:pk>", StorageHoldDetailView.as_view(), name="logistics-holds-detail"),
    path("logistics/events", CollectionEventListCreateView.as_view(), name="logistics-events"),
    path("logistics/events/<int:pk>", CollectionEventDetailView.as_view(), name="logistics-events-detail"),
    path("logistics/events/<int:pk>/route", RouteOptimiseView.as_view(), name="logistics-events-route"),
    # Phase 25 — Semantic Search & Map Discovery
    path("listings/semantic-search", SemanticSearchView.as_view(), name="listings-semantic-search"),
    path("listings/map-data", MapDataView.as_view(), name="listings-map-data"),
    path("listings/trending", TrendingListingsView.as_view(), name="listings-trending"),
    path("saved-searches", SavedSearchListCreateView.as_view(), name="saved-searches-list"),
    path("saved-searches/<int:pk>", SavedSearchDetailView.as_view(), name="saved-searches-detail"),
    path("buildings", BuildingCoordListCreateView.as_view(), name="buildings-list"),
    path("reservations/pickup-route", ProximityRouteView.as_view(), name="reservations-pickup-route"),
    # Phase 21 — Social & Community
    path("leaderboard", LeaderboardView.as_view(), name="leaderboard"),
    path("leaderboard/buildings", BuildingLeaderboardView.as_view(), name="leaderboard-buildings"),
    path("announcements", AnnouncementListCreateView.as_view(), name="announcements-list"),
    path("announcements/<int:pk>", AnnouncementDetailView.as_view(), name="announcements-detail"),
    path("reservations/<int:pk>/thank", ReservationThankView.as_view(), name="reservation-thank"),
    # Phase 27 — White-Label & Partner API
    path("embed/<slug:campus_slug>/listings", EmbedListingsView.as_view(), name="embed-listings"),
    path("campus/<slug:slug>/theme", CampusThemeView.as_view(), name="campus-theme"),
    path("partner/keys", PartnerKeyProvisionView.as_view(), name="partner-keys"),
    path("partner/listings", PartnerListingsView.as_view(), name="partner-listings"),
    path("partner/reservations", PartnerReservationsView.as_view(), name="partner-reservations"),
    path("partner/usage", PartnerUsageView.as_view(), name="partner-usage"),
    path("partner/webhooks", PartnerWebhookListCreateView.as_view(), name="partner-webhooks"),
    path("partner/webhooks/<int:pk>", PartnerWebhookDetailView.as_view(), name="partner-webhooks-detail"),
]
