# Generated by Django 6.0.8 on 2026-09-10 02:17

import django.db.models.deletion
import django.utils.timezone
import risk.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=risk.models._agent_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("daily_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_limit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "requires_approval_above",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("allowed_categories", models.JSONField(blank=True, default=list)),
                ("blocked_merchants", models.JSONField(blank=True, default=list)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=risk.models._inv_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("intent", models.CharField(max_length=40)),
                ("queries", models.JSONField(blank=True, default=list)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("answer", models.TextField()),
                ("facts", models.JSONField(blank=True, default=list)),
                ("inferences", models.JSONField(blank=True, default=list)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("mode", models.CharField(max_length=16)),
                ("model_version", models.CharField(blank=True, max_length=60)),
                (
                    "latency_ms",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_investigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        default=risk.models._evt_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("sequence", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("entity_type", models.CharField(max_length=40)),
                ("entity_id", models.CharField(max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed (will retry)"),
                            ("dead", "Dead-lettered"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("processed_handlers", models.JSONField(blank=True, default=list)),
                ("last_error", models.TextField(blank=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("sequence",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "sequence"],
                        name="risk_event_entity_idx",
                    ),
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="risk_event_status_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-occurred_at"],
                        name="risk_event_type_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=risk.models._txn_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("merchant_id", models.CharField(max_length=80)),
                ("merchant_category", models.CharField(blank=True, max_length=40)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank", "Bank transfer"),
                            ("wallet", "Wallet"),
                            ("campus_credit", "Campus credit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=80)),
                ("ip_prefix", models.CharField(blank=True, max_length=40)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("review", "Under review"),
                            ("blocked", "Blocked"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("allow", "Allow"),
                            ("review", "Review"),
                            ("block", "Block"),
                        ],
                        max_length=8,
                    ),
                ),
                ("risk_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                ("model_version", models.CharField(blank=True, max_length=40)),
                (
                    "evaluation_ms",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("processor_reference", models.CharField(blank=True, max_length=80)),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                ("is_simulation", models.BooleanField(default=False)),
                ("ground_truth_fraud", models.BooleanField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="RiskEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("review", "Review"),
                            ("block", "Block"),
                        ],
                        max_length=8,
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("model_version", models.CharField(max_length=40)),
                ("sensitivity", models.PositiveSmallIntegerField()),
                ("review_threshold", models.PositiveSmallIntegerField()),
                ("block_threshold", models.PositiveSmallIntegerField()),
                ("evaluation_ms", models.DecimalField(decimal_places=3, max_digits=8)),
                ("explanation", models.TextField(blank=True)),
                ("context_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="risk.paymenttransaction",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=160)),
                ("points", models.SmallIntegerField()),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factors",
                        to="risk.riskevaluation",
                    ),
                ),
            ],
            options={
                "ordering": ("-points", "code"),
            },
        ),
        migrations.CreateModel(
            name="RiskPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=80)),
                ("sensitivity", models.PositiveSmallIntegerField(default=50)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=risk.models._sim_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("normal_customer", "Normal customer"),
                            ("card_testing", "Card testing"),
                            ("account_takeover", "Account takeover"),
                            ("new_device_attack", "New device attack"),
                            ("high_velocity", "High velocity attack"),
                            ("suspicious_amount", "Suspicious amount"),
                            ("coordinated_fraud", "Coordinated fraud"),
                            ("multi_account", "Multiple-account attack"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sensitivity", models.PositiveSmallIntegerField()),
                ("seed", models.PositiveIntegerField()),
                ("transaction_count", models.PositiveIntegerField()),
                ("model_version", models.CharField(max_length=40)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                (
                    "duration_ms",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="simulation_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="risk.simulationrun",
            ),
        ),
        migrations.CreateModel(
            name="AgentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("category", models.CharField(max_length=40)),
                ("merchant_id", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("review", "Review"),
                            ("block", "Block"),
                        ],
                        max_length=8,
                    ),
                ),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("risk_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("counts_toward_spend", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="risk.agentpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["agent", "-created_at"], name="risk_agent_txn_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_label", models.CharField(max_length=80)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=40)),
                ("target_id", models.CharField(max_length=40)),
                ("reason", models.TextField(blank=True)),
                ("decision", models.CharField(blank=True, max_length=16)),
                ("model_version", models.CharField(blank=True, max_length=40)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "-created_at"],
                        name="risk_audit_target_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="risk_audit_action_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=255)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="risk.paymenttransaction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="risk_idempotency_expiry_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "scope", "key"), name="risk_idempotency_unique"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="riskevaluation",
            index=models.Index(
                fields=["transaction", "-created_at"], name="risk_eval_txn_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskevaluation",
            index=models.Index(fields=["-created_at"], name="risk_eval_created_idx"),
        ),
        migrations.AddIndex(
            model_name="riskfactor",
            index=models.Index(fields=["code"], name="risk_factor_code_idx"),
        ),
        migrations.AddConstraint(
            model_name="riskpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("sensitivity__gte", 0), ("sensitivity__lte", 100)),
                name="risk_policy_sensitivity_range",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="risk_txn_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["user", "device_id"], name="risk_txn_user_device_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["decision", "-created_at"], name="risk_txn_decision_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["is_simulation", "-created_at"], name="risk_txn_sim_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["device_id", "-created_at"], name="risk_txn_device_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0"))),
                name="risk_txn_amount_positive",
            ),
        ),
    ]
