# Generated by Django 6.0.8 on 2026-09-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentevent",
            name="claim_token",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Claimed by a dispatcher"),
                    ("processed", "Processed"),
                    ("failed", "Failed (will retry)"),
                    ("dead", "Dead-lettered"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
