# Generated by Django 6.0.4 on 2026-04-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonationHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("campus_name", models.CharField(max_length=140)),
                ("zone_label", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("open_instructions", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("is_demo", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("campus_name", "name"),
            },
        ),
    ]
