# Generated by Django 6.0.4 on 2026-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conciergemessage",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
