# Generated by Django 6.0.4 on 2026-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0002_conciergemessage_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="conciergemessage",
            name="rating",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgechunk",
            name="vector_space",
            field=models.CharField(default="hashed-v1", max_length=32),
        ),
    ]
