# Generated by Django 6.0.4 on 2026-04-30 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0001_initial"),
        ("listings", "0002_listingupdate_savedlisting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomScanImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="scan-images/")),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("position", "created_at"),
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="estimated_retail_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.CreateModel(
            name="RoomScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("scanning", "Scanning"),
                            ("clearout", "Clear-Out"),
                            ("completed", "Completed"),
                        ],
                        default="setup",
                        max_length=24,
                    ),
                ),
                ("room_label", models.CharField(max_length=140)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("dorm_room", "Dorm Room"),
                            ("suite", "Suite"),
                            ("apartment", "Apartment"),
                            ("bathroom", "Bathroom"),
                            ("storage_corner", "Storage Corner"),
                        ],
                        default="dorm_room",
                        max_length=24,
                    ),
                ),
                ("pickup_zone", models.CharField(blank=True, max_length=140)),
                ("move_out_deadline", models.DateTimeField(blank=True, null=True)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_scan_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="RoomScanItemDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotspot_box", models.JSONField(default=dict)),
                ("title", models.CharField(max_length=140)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("storage", "Storage"),
                            ("lighting", "Lighting"),
                            ("supplies", "School Supplies"),
                            ("comfort", "Comfort"),
                            ("toiletries", "Toiletries"),
                            ("decor", "Decor"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Like New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("free", "Free"), ("low_cost", "Low Cost")],
                        max_length=24,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "estimated_retail_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "triage_status",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("keep", "Keep"),
                            ("sell", "Sell"),
                            ("donate", "Donate"),
                            ("toss", "Toss"),
                            ("done", "Done"),
                        ],
                        default="review",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donation_hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_donation_items",
                        to="hubs.donationhub",
                    ),
                ),
                (
                    "linked_listing",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_draft_source",
                        to="listings.listing",
                    ),
                ),
                (
                    "source_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_items",
                        to="listings.roomscanimage",
                    ),
                ),
                (
                    "scan_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="listings.roomscansession",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddField(
            model_name="roomscanimage",
            name="scan_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="listings.roomscansession",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="source_scan_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_listings",
                to="listings.roomscansession",
            ),
        ),
    ]
