# Generated by Django 6.0.4 on 2026-04-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_roomscanitemdraft_preset_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoveOutTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("details", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("publish", "Publish"),
                            ("donation", "Donation"),
                            ("pickup", "Pickup"),
                            ("room_reset", "Room Reset"),
                            ("admin", "Admin"),
                        ],
                        default="setup",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=24,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("system_key", models.CharField(blank=True, max_length=32, null=True)),
                ("offset_hours", models.IntegerField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="listings.roomscansession",
                    ),
                ),
            ],
            options={
                "ordering": ("completed_at", "due_at", "created_at"),
            },
        ),
    ]
