# Generated by Django 6.0.4 on 2026-05-01 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_handofffeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RescueRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("storage", "Storage"),
                            ("lighting", "Lighting"),
                            ("supplies", "School Supplies"),
                            ("comfort", "Comfort"),
                            ("toiletries", "Toiletries"),
                            ("decor", "Decor"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("pickup_zone", models.CharField(max_length=140)),
                ("needed_by", models.DateTimeField()),
                (
                    "budget_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("flexible", "Flexible"),
                            ("soon", "Soon"),
                            ("urgent", "Urgent"),
                        ],
                        default="flexible",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("matched", "Matched"),
                            ("fulfilled", "Fulfilled"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_rescue_requests",
                        to="listings.listing",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescue_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("needed_by", "-created_at"),
            },
        ),
    ]
