# Generated by Django 6.0.4 on 2026-05-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_rescuerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
