# Generated by Django 6.0.4 on 2026-05-08 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0001_initial"),
        ("listings", "0011_add_listing_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["is_demo", "status", "available_until"],
                name="listing_active_browse_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["owner", "is_demo", "available_until"],
                name="listing_owner_browse_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category", "status", "available_until"],
                name="listing_category_filter_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moveouttask",
            index=models.Index(
                fields=["scan_session", "status", "due_at"],
                name="task_session_status_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="notification_user_unread_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rescuerequest",
            index=models.Index(
                fields=["status", "needed_by"], name="rescuerequest_open_sort_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rescuerequest",
            index=models.Index(
                fields=["seeker", "status"], name="rescuereq_seeker_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rescuerequest",
            index=models.Index(
                fields=["category", "status", "needed_by"],
                name="rescuerequest_match_center_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["claimant", "status"], name="reservation_claim_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["listing", "status"], name="reservation_listing_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomscanitemdraft",
            index=models.Index(
                fields=["scan_session", "triage_status"],
                name="scanitem_session_triage_idx",
            ),
        ),
    ]
