# Generated by Django 6.0.4 on 2026-05-14 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0002_hub_capacity_and_managers"),
        ("listings", "0030_assistant_thread_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantthread",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Claude-generated summary written at thread end; copied to User.assistant_notes.",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="boosted_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Phase 17: listings boosted via Stripe tip surface first in browse until this datetime.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StorageHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("collected", "Collected"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Hold auto-releases at this time if not collected."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "held_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placed_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_holds",
                        to="hubs.donationhub",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_holds",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CollectionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                (
                    "route_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optimised stop order or building sequence.",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_events",
                        to="hubs.donationhub",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "holds",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collection_events",
                        to="listings.storagehold",
                    ),
                ),
            ],
            options={
                "ordering": ("-scheduled_at",),
            },
        ),
        migrations.AddIndex(
            model_name="storagehold",
            index=models.Index(fields=["hub", "status"], name="hold_hub_status_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionevent",
            index=models.Index(
                fields=["hub", "status", "scheduled_at"],
                name="collection_hub_status_idx",
            ),
        ),
    ]
