# Generated by Django 6.0.4 on 2026-05-14 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_phase25_semantic_search"),
        ("listings", "0031_storage_hold_collection_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="HashingVectorizer feature vector for semantic search similarity ranking.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BuildingCoord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building", models.CharField(db_index=True, max_length=120)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_coords",
                        to="accounts.campus",
                    ),
                ),
            ],
            options={
                "ordering": ["campus", "building"],
                "unique_together": {("campus", "building")},
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("category", models.CharField(blank=True, max_length=24)),
                ("keyword", models.CharField(blank=True, max_length=200)),
                ("price_type", models.CharField(blank=True, max_length=16)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category", "keyword", "price_type"),
                        name="unique_saved_search",
                    )
                ],
            },
        ),
    ]
