# Generated by Django 6.0.4 on 2026-05-14 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0032_phase25_semantic_search"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reservation", "Reservation Confirmed"),
                            ("handoff_urgent", "Handoff Reminder"),
                            ("ai_match", "Match Alert"),
                            ("system", "Listing Expired"),
                            ("weekly_digest", "Weekly Digest"),
                            ("ready_to_publish", "Announcements"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("both", "Push + Email"),
                            ("push", "Push only"),
                            ("email", "Email only"),
                            ("off", "Off"),
                        ],
                        default="both",
                        max_length=8,
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start of quiet window (local time). Null = no quiet hours.",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="End of quiet window (local time). Null = no quiet hours.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "notification_type"],
                        name="notif_pref_user_type_idx",
                    )
                ],
                "unique_together": {("user", "notification_type")},
            },
        ),
    ]
