# Generated by Django 6.0.4 on 2026-07-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0035_listingimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image_thumb",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Auto-generated small rendition of `image` for card grids.",
                null=True,
                upload_to="listing-thumbs/",
            ),
        ),
    ]
