# Generated by Django 6.0.4 on 2026-07-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0036_listing_image_thumb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assistantthread",
            name="user",
        ),
        migrations.DeleteModel(
            name="AssistantMessage",
        ),
        migrations.DeleteModel(
            name="AssistantThread",
        ),
    ]
