# Generated by Django 6.0.4 on 2026-07-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0037_remove_assistantthread_user_delete_assistantmessage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationmessage",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
