# Generated by Django 6.0.8 on 2026-09-08 08:11

from django.conf import settings
from django.db import migrations, models


def cancel_duplicate_active_claims(apps, schema_editor):
    """Keep the oldest live claim per listing; cancel the rest.

    Required before the partial unique index can be created on databases
    that accumulated concurrent double-claims under the old code.
    """
    Reservation = apps.get_model("listings", "Reservation")
    live = ("requested", "confirmed")
    seen = set()
    for reservation in Reservation.objects.filter(status__in=live).order_by("listing_id", "created_at", "id"):
        if reservation.listing_id in seen:
            reservation.status = "cancelled"
            reservation.save(update_fields=["status", "updated_at"])
        else:
            seen.add(reservation.listing_id)


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0038_reservationmessage_read_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 24h handoff reminder was delivered; the idempotency guard for the reminder job.",
                null=True,
            ),
        ),
        migrations.RunPython(cancel_duplicate_active_claims, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("requested", "confirmed"))),
                fields=("listing",),
                name="unique_active_reservation_per_listing",
            ),
        ),
    ]
